# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mariadb:10.9
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MYSQL_DATABASE: CubeTimer
      MYSQL_USER: cubetimer
      MYSQL_PASSWORD: cubetimer
    ports: 
      - 3306:3306
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

        #adminer:
        #  image: adminer
        #  restart: always
        #  ports:
        #    - 8080:8080
